name = "simple-slideshow-hugo"
license = "GNU General Public License v3.0"
licenseLink = "https://github.com/D00NIK/simple-slideshow-hugo/blob/main/LICENSE"
description = "A hugo theme providing a shortcode for creating slideshow galleries"
homepage = "https://github.com/D00NIK/simple-slideshow-hugo"
tags = ["minimal", "gallery"]
features = ["customization", "intuitive", "simple"]

[author]
    name = "Dominik Pakuła"
    homepage = "https://dominikpakula.xyz"
